version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: leonidll/front-end
    ports:
      - "8083:3000"
    volumes:
      - .:/app
    container_name: front-shop
    command: npm start