version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: leonidll/front-main
    ports:
      - "8083:3000"
    volumes:
      - .:/app
    container_name: front-shop
    command: >
      sh -c "npm install && npm start"